{"name": "test_log3", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "test_nav = None\n\n    def test_log3(test_nav):\n        # Navigating to the homepage\n        driver.find_element(By.XPATH, \"//a[contains(text(),'home')]\").click()\n    \n        # Executing the test with incorrect credentials\n        driver.find_element(By.ID, \"email\").send_keys()\n        driver.find_element(By.ID, \"password\").send_keys()\n        driver.find_element(By.XPATH, \"//button[contains(text(),'Login')]\").click()\n        # Wait for the error message to appear\n>       error_message = WebDriverWait(driver, 10).until(\n            EC.visibility_of_element_located((By.CLASS_NAME, \"error-message\"))\n        )\n\nTestcases\\test_Login.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"8e24166e8aaf5957e19bc6b7a49e844a\")>\nmethod = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x000002449B596790>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n..\\..\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "start": 1706866114784, "stop": 1706866126524, "uuid": "61f95d7d-32b3-4ba5-9fe0-4130c83d5175", "historyId": "b124549d4c6ac177de77d5fe6176ab07", "testCaseId": "b124549d4c6ac177de77d5fe6176ab07", "fullName": "Testcases.test_Login#test_log3", "labels": [{"name": "parentSuite", "value": "Testcases"}, {"name": "suite", "value": "test_Login"}, {"name": "host", "value": "EDITH"}, {"name": "thread", "value": "16568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcases.test_Login"}]}